.PHONY: quality

# ARANGO_TEST_URL enables the optional database integration test.
quality:
	@test -z "$$(gofmt -l .)" || { gofmt -l .; exit 1; }
	go vet ./...
	go build ./...
	go test -race -count=1 ./...
	go run honnef.co/go/tools/cmd/staticcheck@2024.1.1 ./...
	go run github.com/kisielk/errcheck@v1.7.0 ./...
