.PHONY: quality

# ARANGO_TEST_URL enables the optional database integration test.
quality:
	@test -z "$$(gofmt -l .)" || { gofmt -l .; exit 1; }
	go vet ./...
	go build ./...
	go test -race -count=1 ./...
	GOTOOLCHAIN=$$(go env GOVERSION) go run honnef.co/go/tools/cmd/staticcheck@v0.8.1 ./...
	GOTOOLCHAIN=$$(go env GOVERSION) go run github.com/kisielk/errcheck@v1.20.0 ./...
